---
title: "Prob switch analyses"
output: html_notebook
---

# Set switches

```{r Set up parameters}
gg_save = T
data = "simulated_human"  # Can be "human", "fitted_human", or "simulated_human"
# parameter_names = c("alpha", "alpha_high", "beta", "beta_high", "epsilon", "TS_bias", "forget")
parameter_names = c('alpha', 'beta', 'nalpha', 'calpha', 'cnalpha')
desired_columns = c("sID", "version", "selected_box", "p_right", "reward", "RT", "correct", "correct_box", "learning_style", "model_name", "NLL", parameter_names, paste0(parameter_names, "_rec"))
colors_3and1 = c("#00D000", "#00C0CC", "#00B0FF", "darkgrey")
library("ggplot2"); theme_set(theme_bw()); library("plyr"); library("reshape2"); library("R.matlab"); library("zoo"); library(lmerTest);# library("lme4")

if (data == "human") {
  # data_dir = "C:/Users/maria/MEGAsync/SLCN/PShumanData"
  data_dir = "C:/Users/maria/MEGAsync/SLCNdata/ProbSwitch"
  patt = "*.mat"
} else if (data == "fitted_human") {
  data_dir = "C:/Users/maria/MEGAsync/SLCN/PSGenRec"
  patt = ".csv"
} else if (data == "simulated_human") {
  model = "Bbpsr"
  data_dir = paste0("C:/Users/maria/MEGAsync/SLCN/PShumanData/fitting/map_indiv/simulations/", model)  # "C:/Users/maria/MEGAsync/SLCN/PSsimulations" # "C:/Users/maria/MEGAsync/SLCN/PShumanData/fit_par/simulations"
  patt = paste0(model, ".*csv")
}
plot_dir = file.path(data_dir, paste0("Plots_", model))
# plot_dir = "C:/Users/maria/MEGAsync/SLCNdata/ProbSwitch/PS_plots"

if (!dir.exists(plot_dir)) {
  dir.create(plot_dir)
}
```

# Read in and clean data

```{r Read in ages}
# if (data %in% c("human", "fitted_human")) {
  ages = read.csv("C:/Users/maria/MEGAsync/SLCNdata/SLCNinfo2.csv")
  colnames(ages)[colnames(ages) == "ID"] = "sID"
# } else {
#   ages = read.csv("C:/Users/maria/MEGAsync/SLCN/models/ages.csv")
#   colnames(ages)[colnames(ages) == "age"] = "PreciseYrs"
#   ages$X = NULL
# }
  
# subset(ages, !Gender %in% c(1, 2))  # IDs 307 & 336 are "3"?! asked Sarah 3/19/2019
# subset(ages, is.na(Columbia_cat))  # subjects 11-16, 34 and 55 are missing PDS
# subset(ages, Gender==1 & PDS >3.5)  # we only have 1 boy with PDS > 3.5, but 22 girls

ages$age_group = NA
ages$age_group[ages$PreciseYrs > 20] = "25-30"
ages$age_group[ages$PreciseYrs < 18] = "15-17"
ages$age_group[ages$PreciseYrs < 15] = "11-14"
ages$age_group[ages$PreciseYrs < 11] = "7-10"
ages$PDS[ages$age_group == "25-30"] = 6
ages$Gender = factor(ages$Gender, levels=c(1, 2, 3), labels=c("Male", "Female", NA))
ages$Columbia_cat[ages$sID >= 300] = 10
ages$Columbia_cat = factor(ages$Columbia_cat, labels=c("Pre", "Pub", "Post", "Adult", NA))

# Add testost. group
ages$T134 = rowMeans(subset(ages, select=c(T1, T3, T4)), na.rm=T)
ages$log_T = log(ages$T134)
ggplot(ages, aes(T134, fill=Gender)) + geom_histogram(bins=15, position = position_dodge())

make_groups = function(ages, colname, probs=c(1, 2/3, 1/3)) {
  
  quantiles_f = quantile(ages[ages$sID < 300 & ages$Gender=="Female", colname], probs=probs, na.rm=T)
  quantiles_m = quantile(ages[ages$sID < 300 & ages$Gender=="Male", colname], probs=probs, na.rm=T)
  
  groups = rep(NA, nrow(ages))
  for (i in 1:length(probs)) {
    groups[ages$Gender=="Female" & ages[,colname] <= quantiles_f[i]] = paste0(round(100*probs[i], digits=1), "%")
    groups[ages$Gender=="Male" & ages[,colname] <= quantiles_m[i]] = paste0(round(100*probs[i], digits=1), "%")
  }
  groups[ages$sID >= 300] = "Adult"
  groups = factor(groups, levels=c("33.3%", "66.7%", "100%", "Adult"))
  
  return(groups)
}

ages$T_group = make_groups(ages, "T134")
ages$PDS_group = make_groups(ages, "PDS")

ddply(ages, .(T_group, Gender), T=min(T134, na.rm=T), summarize)  # check that assignment was right (min matches up with quantiles)

# Add PDS group
ages$PDS_group

ggplot(ages, aes(Columbia_cat)) +
  geom_histogram(stat="count") +
  facet_grid(~ Gender)

ggplot(ages, aes(PDS)) +
  geom_histogram() +
  facet_grid(~ Gender)
```
```{r Read in data}
all_files = data.frame()

filenames = list.files(data_dir, pattern = patt)
print(paste(length(filenames), "filenames on the list."))
filename = filenames[1]  # debugging

for(filename in filenames) {
  
  if (data == "human") {
    mat_file = readMat(file.path(data_dir, filename))$exp[,,1]$PROBSWITCHdata[,,1]
    subj_file = data.frame(RT = t(mat_file$RT))
    subj_file$selected_box = (t(mat_file$key) - 10) / 2  # recode to make key left==0 and key right==1 (initially key right==12; key left==10)
    subj_file$reward = t(mat_file$reward)  # reward==1, no reward==0
    subj_file$correct_box = 1 - t(mat_file$better.box.left)  # recode to make left==0 and right==1 (initially the opposite)
    sID = as.numeric(strsplit(strsplit(filename, split = "PROBSWITCH_")[[1]][2], ".mat")[[1]])
    subj_file$sID = sID
    subj_file = subset(subj_file, !is.nan(reward) & selected_box %in% c(0, 1))  # remove no-response trials
    subj_file = subj_file[47:nrow(subj_file),]  # needs to be changed for future participants - 51
  } else {
    subj_file = read.csv(file.path(data_dir, filename))
  }
  
  # Make sure all files have the same columns
  ## Remove unwanted columns
  for (col_name in colnames(subj_file)) {
    if (!col_name %in% desired_columns) {
      subj_file[,col_name] = NULL
    }
  }
  ## Add NA columns for wanted columns
  for (col_name in desired_columns) {
    if (!col_name %in% colnames(subj_file)) {
      subj_file[,col_name] = NA
    }
  }
  if (is.na(subj_file$model_name[1])) {
    subj_file$model_name = subj_file$learning_style
  }
  if (is.na(subj_file$model_name[1])) {
    subj_file$model_name = "no_model"
  }
  if (is.na(subj_file$version[1])) {
    subj_file$version = "no_version"
  }
  
  # Add columns
  subj_file$TrialID = 1:nrow(subj_file)
  subj_file$rewardversion = subj_file$sID %% 4
  subj_file$ACC = with(subj_file, selected_box == correct_box)
  
  # Get switch_trial, block, and trialssinceswitch
  this_trial = subj_file$correct_box[2:nrow(subj_file)]
  prev_trial = subj_file$correct_box[1:(nrow(subj_file) - 1)]
  subj_file$switch_trial = c(F, this_trial != prev_trial)
  subj_file$block = cumsum(subj_file$switch_trial)
  
  subj_file$trialsinceswitch = NA
  for (blocki in subj_file$block) {
    n_rows = nrow(subset(subj_file, block == blocki))
    if (n_rows >= 4) {
      subj_file$trialsinceswitch[subj_file$block == blocki] = 0:(n_rows - 1)
      subj_file$trialsinceswitch[subj_file$block == blocki][(n_rows - 3):n_rows] = -4:-1
    }
  }
  
  subj_file$outcome_1_back = c(NA, subj_file$reward[1:(nrow(subj_file) - 1)])
  subj_file$outcome_2_back = c(NA, NA, subj_file$reward[1:(nrow(subj_file) - 2)])
  
  subj_file$choice_left = subj_file$selected_box == 0  # left: 0; right: 1
  subj_file$choice_1_back = c(NA, subj_file$choice_left[1:(nrow(subj_file) - 1)])
  subj_file$choice_2_back = c(NA, NA, subj_file$choice_left[1:(nrow(subj_file) - 2)])
  
  if (data == "human") {
    write.csv(subj_file, paste(data_dir, "/PS_", sID, ".csv", sep = ""), row.names = F)
  }
  
  all_files = as.data.frame(rbind(all_files, subj_file))
}

reward_versions = ddply(all_files, .(sID), summarize, rewardversion = rewardversion[1])
write.csv(reward_versions, paste0(data_dir, "_rewardversions.csv"))
print(paste("Red in data from", length(unique(all_files$sID)), "subjects"))
summary(all_files)
summary(subj_file)
colnames(all_files)
```
```{r Remaining fixes for all_filess}
all_files$outcome_21_back = paste(all_files$outcome_2_back, all_files$outcome_1_back)
all_files$outcome_21_back = factor(all_files$outcome_21_back,
                                   levels = c("1 1", "0 1", "1 0", "0 0"),
                                   labels = c("both reward", "no reward, reward", "reward, no reward", "both no reward"))
all_files$same_choice_01_back = all_files$choice_left == all_files$choice_1_back  # same choice in this trial as in the last?
all_files$same_choice_12_back = all_files$choice_1_back == all_files$choice_2_back  # same choice in this trial as in the last?
all_files$choice_12_back = ifelse(all_files$choice_1_back, "left", "right")
all_files$choice_12_back[!all_files$same_choice_12_back | is.na(all_files$same_choice_12_back)] = NA
all_files$reward_port = factor(all_files$correct_box, levels = c(0, 1), labels = c("Left", "Right"))
all_files$learning_style = factor(all_files$learning_style)

old_nrows = nrow(all_files)
all_files = merge(all_files, ages, all.x = T)
# all_files$Columbia_cat = factor(all_files$Columbia_cat)
# all_files$age_group = as.character(all_files$age_group)
all_files$age_group = factor(as.character(all_files$age_group), levels = c("7-10", "11-14", "15-17", "25-30"))
assertthat::assert_that(nrow(all_files) == old_nrows)
# summary(all_files)

all_files = subset(all_files, !is.na(PreciseYrs) & !is.na(PDS))

xyz = ddply(all_files, .(sID, Gender, age_group), x = NA, summarize)
ddply(xyz, .(age_group, Gender), summarize, n=length(age_group))
```

# Composition of our sample

```{r Sample composition}
gg_PDS_composition =
  ggplot(ddply(all_files, .(sID, PDS, Gender, T134, PreciseYrs), summarize, z=NA), aes(x=factor(1), fill=factor(round(PDS*4)/4))) +
  geom_bar(width=1) + coord_polar("y") +
  labs(fill="PDS") +
  facet_grid(~ Gender)

gg_age_composition = gg_PDS_composition + aes(fill=factor(round(PreciseYrs))) + labs(fill="Age")
gg_T_composition = gg_PDS_composition + aes(fill=factor(round(log(T134)*3)/3)) + labs(fill="log. Testost.")

if (gg_save) {
  if (data %in% c("human", "fitted_human")) {
    ggsave(file.path(plot_dir, "/gg_PDS_composition.png"), gg_PDS_composition, width=4, height=2)
    ggsave(file.path(plot_dir, "/gg_age_composition.png"), gg_age_composition, width=4, height=2)
    ggsave(file.path(plot_dir, "/gg_T_composition.png"), gg_T_composition, width=6, height=3)
  }
}
```
```{r Relationship between predictors}
dat = subset(ages, sID < 300)
gg_age_PDS = ggplot(dat, aes(PreciseYrs, PDS, color=Gender)) +
  geom_point(size=0.4) +
  scale_color_manual(values=c("red", "orange")) +
  labs(x="Age", y="PDS", color="Sex")
gg_age_T = gg_age_PDS + aes(PreciseYrs, log_T) + labs(x="Age", y="Testost.", color="Sex")
gg_PDS_T = gg_age_PDS + aes(PDS, log_T) + labs(x="PDS", y="Testost.", color="Sex")

pairs(ages[ages$sID < 300, c("PreciseYrs", "PDS", "log_T")], pch = 19, lower.panel=NULL, col=ages$Gender)

for (gender in levels(dat$Gender)[1:2]) {
  print(gender)
  dat_ = subset(dat, Gender==gender)
  print(cor.test(dat_$PreciseYrs, dat_$log_T))
  print(cor.test(dat_$PreciseYrs, dat_$PDS))
  print(cor.test(dat_$log_T, dat_$PDS))
}

# plotmatrix(ages[ages$sID < 300, c("PreciseYrs", "PDS", "log_T")])

ggsave(file.path(plot_dir, "/gg_age_PDS.png"), gg_age_PDS, width=3, height=2)
ggsave(file.path(plot_dir, "/gg_age_T.png"), gg_age_T, width=3, height=2)
ggsave(file.path(plot_dir, "/gg_PDS_T.png"), gg_PDS_T, width=3, height=2)
```

# Analyze behavior

```{r Get behavioral summary and win-stay loose-shift}
# Behavior
## Summarize over individual simulations of the same participant (necesary for simulated_humans - should not do anything for the other datasets)
all_files_sum_pre = ddply(subset(all_files, !is.na(choice_12_back)),
                      .(sID, version, age_group, Columbia_cat, T_group, model_name, outcome_21_back, choice_12_back), summarize,
                      choice_left = mean(choice_left, na.rm = T))
all_files_sum = ddply(all_files_sum_pre,
                      .(sID, age_group, Columbia_cat, T_group, model_name, outcome_21_back, choice_12_back), summarize,
                      choice = mean(choice_left, na.rm = T))
all_files_sum2_pre = ddply(subset(all_files, !is.na(trialsinceswitch)),
                       .(sID, version, age_group, T_group, model_name, trialsinceswitch), summarize,
                       choice_left = mean(choice_left, na.rm = T),
                       RT = median(RT, na.rm = T))
all_files_sum2 = ddply(all_files_sum2_pre,
                       .(sID, age_group, T_group, model_name, trialsinceswitch), summarize,
                       choice = mean(choice_left, na.rm = T),
                       RT = median(RT, na.rm = T))
# Win-stay loose-shift
stay = with(all_files, c(choice_left == choice_1_back))
all_files$stay = c(stay[2:length(stay)], NA)
all_files$stay[all_files$TrialID == 1] = NA  # first trial is no stay - doing this is faster than looping
wsls_pre = ddply(all_files, .(sID, Gender, version, reward, age_group), summarize,
             stay = mean(stay, na.rm = T))
wsls = ddply(wsls_pre, .(sID, Gender, reward, age_group), summarize,
             stay = mean(stay, na.rm = T))
wsls$reward = factor(wsls$reward)

colnames(all_files)
switch_counts = ddply(all_files, .(sID, PreciseYrs, age_group), summarize, n_switches=sum(switch_trial, na.rm=T))
mean(switch_counts$n_switches)
sd(switch_counts$n_switches)
ggplot(switch_counts, aes(PreciseYrs, n_switches)) + geom_point()
```
```{r Basic behavioral analyses}
# Response times
gg_RT = ggplot(all_files, aes(TrialID, RT, fill = age_group)) +
  # geom_point() +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "bar", position = position_dodge(width = 0.9)) +
  facet_grid(~ age_group)
# gg_RT_PDS = gg_RT + aes(fill=Columbia_cat) + facet_grid(~ Columbia_cat)

gg_RTt = ggplot(all_files_sum2, aes(trialsinceswitch, RT, fill = age_group)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "bar", position = position_dodge(width = 0.9)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange", position = position_dodge(width = 0.9)) +
  # geom_point(alpha = .3, position = "jitter") +
  coord_cartesian(x = c(-3, 5)) +
  facet_grid(~ age_group)

# ACC over trials
gg_ACC = ggplot(all_files, aes(TrialID, 100 * as.numeric(ACC), fill = age_group)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "bar") +
  labs(y = "% correct", fill = "Age") +
  facet_grid(model_name ~ age_group)

# Choice over blocks
gg_choice_blocks = ggplot(subset(all_files, !is.na(choice_left)),
                       aes(trialsinceswitch, 100 * choice_left, color = reward_port, group = reward_port, shape = age_group)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange") +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "line") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  coord_cartesian(x = c(-3, 7)) +
  labs(x = "Trials since switch", y = "% choice left", color = "Reward port", shape = "") +
  facet_grid(model_name ~ age_group)
# gg_choice_blocks_PDS = gg_choice_blocks + aes(shape=factor(Columbia_cat)) + facet_grid(model_name ~ Columbia_cat)

# ACC over blocks
ACC_subj = ddply(all_files, .(sID, Gender, T_group, log_T, age_group, PDS_group, PDS, PreciseYrs, Columbia_cat, trialsinceswitch, model_name), summarize, ACC = mean(ACC, na.rm=T))  # to make sure error bars are right
gg_ACC_blocks =
  ggplot(ACC_subj, aes(trialsinceswitch, 100 * ACC, group = age_group, color = age_group)) + 
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "pointrange", size=0.1) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "line") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  coord_cartesian(x = c(-3, 7), y = c(0, 100)) +
  scale_x_continuous(breaks = seq(-3, 7, 2)) +
  # scale_color_brewer(palette='Blues') +
  scale_color_manual(values=colors_3and1) +
  labs(x = "Trials since switch", y = "% correct", color = "Age", shape = "Age") +
  facet_grid(Gender ~ model_name)
gg_ACC_blocks_PDS = gg_ACC_blocks + aes(group=PDS_group, color=PDS_group) + labs(color="PDS")
gg_ACC_blocks_T = gg_ACC_blocks + aes(group=T_group, color=T_group) + labs(color="Testost.")
gg_ACC_blocks_T$data = subset(gg_ACC_blocks$data, !is.na(T_group))

dat1 = subset(ACC_subj, trialsinceswitch == 1)
# t.test(ACC ~ age_group, data=subset(dat1, age_group %in% c("7-12", "25-30")))
# t.test(ACC ~ age_group, data=subset(dat1, age_group %in% c("7-12", "13-17")))
# t.test(ACC ~ age_group, data=subset(dat1, age_group %in% c("13-17", "25-30")))
# summary(lm(ACC ~ PreciseYrs, dat=subset(dat1, PreciseYrs<24)))  # quadratic effect?

dat37 = subset(ACC_subj, trialsinceswitch %in% c(3, 4, 5, 6, 7))
dat37 = ddply(dat37, .(sID, age_group, PreciseYrs), summarize, ACC=mean(ACC,na.rm=T))
# t.test(ACC ~ age_group, data=subset(dat37, age_group %in% c("7-12", "25-30")))
# t.test(ACC ~ age_group, data=subset(dat37, age_group %in% c("7-12", "13-17")))
# t.test(ACC ~ age_group, data=subset(dat37, age_group %in% c("13-17", "25-30")))
# summary(lm(ACC ~ PreciseYrs, dat=subset(dat37, PreciseYrs<24)))  # quadratic effect?

# Response times
gg_RT_blocks = gg_choice_blocks + aes(y = RT) + coord_cartesian(x = c(-3, 7), y = c(250, 650))

# Rewards over trials
gg_rewards = ggplot(all_files, aes(TrialID, 100 * reward, fill = age_group)) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1), geom = "bar") +
  labs(y = "% reward received", fill = "Age") +
  facet_grid(model_name ~ age_group)

# Choice depending on previous outcome
gg_rewards2 = ggplot(subset(all_files_sum, !is.na(choice_12_back)),
                     aes(outcome_21_back, 100 * choice, fill = choice_12_back, group = choice_12_back, shape = age_group)) +
  stat_summary(fun.data = mean_cl_normal, geom = "bar", fun.args = list(mult = 1), position = "dodge") +
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", fun.args = list(mult = 1), position = position_dodge(0.9)) +
  coord_cartesian(y = c(0, 100)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) +
  labs(x = "Reward history (1 trial back, 2 trials back)", y = "% left choice", fill = "Previous two choices", shape = "Age") +
  facet_grid(model_name ~ age_group)
# gg_rewards2_PDS = gg_rewards2 + aes(shape=factor(Columbia_cat)) + facet_grid(model_name ~ Columbia_cat)

# Choice depending on previous outcome (collapsed)
# sub = subset(all_files, !is.na(outcome_21_back), select = c("sID", "TrialID", "choice_left", "choice_1_back", "stay", "same_choice_01_back", "outcome_21_back"))
# sub[order(sub$sID, sub$TrialID), ]
reward_subj = ddply(subset(all_files, !is.na(outcome_21_back)),
                    .(sID, Gender, PDS, T_group, PDS_group, log_T, Columbia_cat, outcome_21_back, age_group, model_name, PreciseYrs), summarize, stay = mean(same_choice_01_back, na.rm = T))

# summary(lmer(same_choice_01_back ~ PreciseYrs + (1 | sID), subset(all_files, outcome_21_back=='both reward')))
# summary(lmer(same_choice_01_back ~ PreciseYrs + (1 | sID), subset(all_files, outcome_21_back=='no reward, reward')))
# summary(lmer(same_choice_01_back ~ PreciseYrs + (1 | sID), subset(all_files, outcome_21_back=='both no reward')))

stay_plot =
  ggplot(reward_subj, aes(outcome_21_back, 100 * stay, fill = age_group)) +
  stat_summary(fun.data = mean_cl_normal, geom = "bar", fun.args = list(mult = 1), position = "dodge") +
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", fun.args = list(mult = 1), position = position_dodge(0.9), size=0.1) +
  theme(axis.text.x = element_text(angle = -30, hjust = 0.2)) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_manual(values=colors_3and1) +
  labs(x = "Previous outcomes", y = "% stay", fill = "Age") +
  facet_grid(Gender ~ model_name)
stay_plot_PDS = stay_plot + aes(group=PDS_group, fill=PDS_group) + labs(fill="PDS")
stay_plot_T = stay_plot + aes(group=T_group, fill=T_group) + labs(fill="Testost.")  # make sure i'm not introducing NAs: mean(is.na(log(all_files$log_T)) == is.na(all_files$log_T))
stay_plot_T$data = subset(stay_plot$data, !is.na(T_group))

if (gg_save) {
  if (data %in% c("human", "fitted_human")) {
    ggsave(file.path(plot_dir, "/gg_RT.png"), gg_RT)
    ggsave(file.path(plot_dir, "/gg_RTt.png"), gg_RTt)
    ggsave(file.path(plot_dir, "/gg_ACC.png"), gg_ACC)
    ggsave(file.path(plot_dir, "/gg_RT_blocks.png"), gg_RT_blocks, width = 8, height = 3)
  }
  ggsave(file.path(plot_dir, "/gg_choice_blocks.png"), gg_choice_blocks, width = 8, height = 1 + 2 * length(unique(gg_choice_blocks$data$model_name)))
  ggsave(file.path(plot_dir, "/gg_rewards.png"), gg_rewards)
  ggsave(file.path(plot_dir, "/gg_rewards2.png"), gg_rewards2, width = 8, height = 1.4 + 2 * length(unique(gg_ACC_blocks$data$model_name)))
  ggsave(file.path(plot_dir, "/gg_ACC_blocks.png"), gg_ACC_blocks, width = 3.3, height = 2 + length(unique(gg_ACC_blocks$data$model_name)))
  ggsave(file.path(plot_dir, "/gg_ACC_blocks_PDS.png"), gg_ACC_blocks_PDS, width = 3.3, height = 2 + length(unique(gg_ACC_blocks$data$model_name)))
  ggsave(file.path(plot_dir, "/gg_ACC_blocks_T.png"), gg_ACC_blocks_T, width = 3.3, height = 2 + length(unique(gg_ACC_blocks$data$model_name)))
  ggsave(file.path(plot_dir, "/stay_plot.png"), stay_plot, width = 3.3, height = 2.2 + length(unique(stay_plot$data$model_name)))
  ggsave(file.path(plot_dir, "/stay_plot_PDS.png"), stay_plot_PDS, width = 3.3, height = 2.2 + length(unique(stay_plot$data$model_name)))
  ggsave(file.path(plot_dir, "/stay_plot_T.png"), stay_plot_T, width = 3.3, height = 2.2 + length(unique(stay_plot$data$model_name)))
}
```
```{r Following up on switch trials}
gg_ACC1trialswitch_age =
  ggplot(subset(ACC_subj, trialsinceswitch==1 & PreciseYrs < 20), aes(PreciseYrs, ACC, color=Gender)) +
  geom_point() +
  labs(y="Acc trial 1 after swtich") +
  geom_smooth(method='lm')
gg_ACC1trialswitch_PDS = gg_ACC1trialswitch_age + aes(PDS)
gg_ACC1trialswitch_T = gg_ACC1trialswitch_age + aes(log_T)

kid_rewnorew_dat = subset(reward_subj, outcome_21_back=='reward, no reward' & PDS < 6)
gg_stayrewnorew_PDS = ggplot(kid_rewnorew_dat, aes(PDS, stay)) +
  geom_point() +
  geom_smooth(method='lm', color='darkgrey') +
  labs(y="% stay after 'reward, no reward'") +
  facet_grid(~ Gender)
gg_stayrewnorew_age = gg_stayrewnorew_PDS + aes(PreciseYrs, stay)
gg_stayrewnorew_T = gg_stayrewnorew_PDS + aes(log_T, stay)

gg_11to14_PDS = 
  ggplot(subset(kid_rewnorew_dat, PreciseYrs >= 11 & PreciseYrs <= 14), aes(PDS, stay, color=Gender)) +
  geom_point() +
  geom_smooth(method='lm') +
  labs(x="PDS", y="% stay after 'reward, no reward'")
gg_11to14_T = gg_11to14_PDS + aes(log_T)

# summary(glmer(ACC ~ PreciseYrs_z * T1_z + (1 | sID) + (1 | Gender), reg_dat, binomial))
for (gender in levels(all_files$Gender)[1:2]) {
  print(gender)
  print(summary(glmer(stay ~ PreciseYrs + PDS + log_T + (1 | sID) + (1 | Gender), subset(all_files, outcome_21_back=='reward, no reward' & sID < 300), binomial)))
  print(summary(glmer(stay ~ PreciseYrs + PDS + log_T + (1 | sID), subset(all_files, outcome_21_back=='reward, no reward' & Gender==gender & sID < 300), binomial)))
  print(summary(lmer(stay ~ PreciseYrs + PDS + log_T + (1 | Gender), kid_rewnorew_dat)))
  print(summary(lm(stay ~ PreciseYrs + PDS + log_T, subset(kid_rewnorew_dat, Gender==gender))))
}

if (gg_save) {
  if (data %in% c("human", "fitted_human")) {
    ggsave(file.path(plot_dir, "/gg_ACC1trialswitch_age.png"), gg_ACC1trialswitch_age)
    ggsave(file.path(plot_dir, "/gg_ACC1trialswitch_PDS.png"), gg_ACC1trialswitch_PDS)
    ggsave(file.path(plot_dir, "/gg_ACC1trialswitch_T.png"), gg_ACC1trialswitch_T)
    ggsave(file.path(plot_dir, "/gg_stayrewnorew_PDS.png"), gg_stayrewnorew_PDS)
    ggsave(file.path(plot_dir, "/gg_stayrewnorew_age.png"), gg_stayrewnorew_age)
    ggsave(file.path(plot_dir, "/gg_stayrewnorew_T.png"), gg_stayrewnorew_T)
    ggsave(file.path(plot_dir, "/gg_11to14_PDS.png"), gg_11to14_PDS)
    ggsave(file.path(plot_dir, "/gg_11to14_T.png"), gg_11to14_T)
  }
}
```
```{r WSLS}
gg_wsls = ggplot(wsls, aes(reward == 1, stay, color = reward == 1, shape = age_group)) +
  stat_summary(fun.data = "mean_se", geom = "pointrange") +
  geom_point(alpha = 0.5, position = "jitter") +
  labs(x = "Reward", y = "% stay trials", color = "Reward", shape = "Age") +
  facet_grid(Gender ~ age_group)
if (data == "fitted_sim") {
  gg_wsls = gg_wsls + facet_grid(learning_style ~ method)
}

if (gg_save) {
  ggsave(file.path(plot_dir, "/gg_wsls.png"), gg_wsls)
}
summary(all_files)
```

```{r regression ACC / RT ~ age * testosterone}
# Vizualize effects of age and testosterone on ACC & RT
median_RT = ddply(subset(all_files, ACC=T), .(sID, Gender, PreciseYrs, log_T), RT=median(RT), log_T=median(log_T), z=NA, summarize)
# gg_age_testosterone =
  ggplot(median_RT, aes(PreciseYrs, log_T, color=Gender)) + geom_point()

# gg_age_RT =
  ggplot(subset(median_RT, PreciseYrs<24), aes(PreciseYrs, RT, color=log_T)) + geom_point() + geom_smooth()
# gg_T_RT =
  ggplot(subset(median_RT, PreciseYrs<24), aes(log_T, RT, color=Gender)) + geom_point() + geom_smooth()

# gg_age_RT =
  ggplot(subset(median_RT, PreciseYrs>=11 & PreciseYrs<=14), aes(PreciseYrs, RT, color=log_T)) + geom_point() + geom_smooth()
# gg_T_RT =
  ggplot(subset(median_RT, PreciseYrs>=11 & PreciseYrs<=14), aes(log_T, RT, color=Gender)) + geom_point() + geom_smooth()

mean_ACC = ddply(all_files, .(sID, Gender, PreciseYrs, log_T), ACC=mean(ACC), log_T=median(log_T), summarize)
# gg_age_ACC =
  ggplot(subset(mean_ACC, PreciseYrs<24), aes(PreciseYrs, ACC, color=log_T)) + geom_point() + geom_smooth()
# gg_T_ACC =
  ggplot(subset(mean_ACC, PreciseYrs<24), aes(log_T, ACC, color=Gender)) + geom_point() + geom_smooth()
  
# gg_T_PDS =
  ggplot(subset(all_files, PreciseYrs<20), aes(PDS, log_T, color=PreciseYrs, shape=factor(Gender))) + geom_point()

# z-score predictors
# Calculate regression models
reg_dat = subset(all_files, age_group!="25-30")
# reg_dat = subset(all_files, PreciseYrs>=11 & PreciseYrs<=14)
# reg_dat = subset(all_files, PreciseYrs<20)
reg_dat$PreciseYrs_z = (reg_dat$PreciseYrs - mean(reg_dat$PreciseYrs, na.rm=T)) / sd(reg_dat$PreciseYrs, na.rm=T)
reg_dat$T1_log = log(reg_dat$T1)
reg_dat$T1_z = (reg_dat$T1_log - mean(reg_dat$T1_log, na.rm=T)) / sd(reg_dat$T1_log, na.rm=T)
reg_dat$Gender = factor(reg_dat$Gender)
reg_dat$log_RT = log(reg_dat$RT)
# reg_dat$pub = (log(reg_dat$T1) - mean(log(reg_dat$T1), na.rm=T)) / sd(log(reg_dat$T1), na.rm=T) + (reg_dat$PDS - mean(reg_dat$PDS, na.rm=T)) / ggplot(reg_dat, aes(PreciseYrs, pub)) + geom_point()
hist(reg_dat$RT)
hist(reg_dat$log_RT)
summary(lmer(log_RT ~ PreciseYrs_z * T1_z + (1 | sID) + (1 | Gender), subset(reg_dat, ACC==T), na.action=na.omit, REML=F, verbose=T))
summary(glmer(ACC ~ PreciseYrs_z * T1_z + (1 | sID) + (1 | Gender), reg_dat, binomial))

summary(lmer(log_RT ~ PreciseYrs_z + (1 | sID) + (1 | Gender), subset(reg_dat, ACC==T), na.action=na.omit, REML=F, verbose=T))
summary(glmer(ACC ~ PreciseYrs_z + (1 | sID) + (1 | Gender), reg_dat, binomial))

summary(lmer(log_RT ~ PreciseYrs_z * T1_z + (1 | sID), subset(reg_dat, ACC==T & Gender=="Female"), na.action=na.omit, REML=F, verbose=T))
summary(lmer(log_RT ~ PreciseYrs_z * T1_z + (1 | sID), subset(reg_dat, ACC==T & Gender=="Male"), na.action=na.omit, REML=F, verbose=T))
summary(glmer(ACC ~ PreciseYrs_z * T1_z + (1 | sID), subset(reg_dat, Gender=="Female"), binomial))
summary(glmer(ACC ~ PreciseYrs_z * T1_z + (1 | sID), subset(reg_dat, Gender=="Male"), binomial))

# summary(subset(reg_dat, is.na(T1), select=c("RT", "log_RT", "T1", "T1_z", "PreciseYrs", "PreciseYrs_z"))$T1_z)
# summary(reg_dat)
```

# Run regression models

```{r Prepare data for regression}
# Prepare data
all_files_regr = subset(all_files, select = c("sID", "version", "model_name", "TrialID", "block", "reward", "selected_box"))
## Times rewarded and times selected
all_files_regr$selected = as.numeric(as.character(factor(all_files_regr$selected_box, levels = c(0, 1), labels = c(-1, 1))))  # 0 / -1: left; +1: right
## Choice regressors
all_files_regr$right_rew = all_files_regr$selected_box
all_files_regr$right_rew[all_files_regr$reward == 0] = -all_files_regr$right_rew[all_files_regr$reward == 0]
all_files_regr$left_rew = 1 - all_files_regr$selected_box
all_files_regr$left_rew[all_files_regr$reward == 0] = -all_files_regr$left_rew[all_files_regr$reward == 0]
## Reward regressors
all_files_regr$reward = all_files_regr$reward
all_files_regr$reward[all_files_regr$selected_box == 0] = -all_files_regr$reward[all_files_regr$selected_box == 0]
all_files_regr$noReward = 1 - all_files_regr$reward
all_files_regr$noReward[all_files_regr$selected_box == 0] = -all_files_regr$noReward[all_files_regr$selected_box == 0]
all_files_regr$selected_box = factor(all_files_regr$selected_box)
all_files_regr
```

```{r Run regression action ~ action_nback * reward_nback and save in nback_regr_dat}
# Run regression models for each subject, for each n in n-back
sel_rew_predictors = c("selected", "reward")
choice_predictors = c("left_rew", "right_rew")
reward_predictors = c("reward", "noReward")

nback_regr_dat = data.frame()
for (subj in unique(all_files_regr$sID)) {
  for (versi in unique(all_files_regr$version)) {
    for (model in unique(all_files_regr$model_name)) {
      for (n in 1:12) {
        subj_dat = subset(all_files_regr, sID == subj & version == versi & model_name == model, !is.na(selected_box))
        
        if (nrow(subj_dat) > 0) {
        
          ## Add nback columns
          for (cond in c(choice_predictors, reward_predictors, sel_rew_predictors)) {
            col_name = paste0("back", n, cond)
            subj_dat[,col_name] = c(rep(NA, n), subj_dat[1:(nrow(subj_dat)-n), cond])
          }
          
          ## Selected/rewarded model (predictors: selected [left: -1, right: +1], reward [left: -1, right: +1, none: 0])
          sel_rew_formula = paste("selected_box ~", paste(paste0("back", n, sel_rew_predictors), collapse = " + "), "+ (1 | block)")
          sel_rew_mod = glm(as.formula(sel_rew_formula),
                    family = "binomial",
                    data = subj_dat)
          sel_rew_coefs = as.data.frame(summary(sel_rew_mod)$coef)
          sel_rew_coefss = cbind(sID = subj, version = versi, model_name = model, model = "selectedRewarded", predictor = rownames(sel_rew_coefs), back = n, data.frame(sel_rew_coefs, row.names = NULL))
          
          ## Choice model (predictors: left_rew [reward: +1, no reward: -1, none: 0], right_rew [reward: +1, no reward: -1, none: 0])
          choice_formula = paste("selected_box ~ ", paste(paste0("back", n, choice_predictors), collapse = " + "))
          choice_mod = glm(as.formula(choice_formula),
                    family = "binomial",
                    data = subj_dat)
          choice_coefs = as.data.frame(summary(choice_mod)$coef)
          choice_coefss = cbind(sID = subj, version = versi, model_name = model, model = "leftRight", predictor = rownames(choice_coefs), back = n, data.frame(choice_coefs, row.names = NULL))
      
          ## Reward model (predictors: reward [left: -1, right: +1, none: 0], no reward [left: -1, right: +1, none: 0])
          reward_formula = paste("selected_box ~", paste(paste0("back", n, reward_predictors), collapse = " + "))
          reward_mod = glm(as.formula(reward_formula),
                    family = "binomial",
                    data = subj_dat)
          reward_coefs = as.data.frame(summary(reward_mod)$coef)
          reward_coefss = cbind(sID = subj, version = versi, model_name = model, model = "rewardNoReward", predictor = rownames(reward_coefs), back = n, data.frame(reward_coefs, row.names = NULL))
          
          nback_regr_dat = rbind(nback_regr_dat, choice_coefss, reward_coefss, sel_rew_coefss)
        }
      }
    }
  }
}
# Beautify
nback_regr_dat = merge(nback_regr_dat, ages, all.x = T)
nback_regr_dat$predictor = gsub("back.", "", nback_regr_dat$predictor)
nback_regr_dat$predictor = gsub("[0-99]", "", nback_regr_dat$predictor)
nback_regr_dat$sig_Estimate = 1 / (1 + exp(-nback_regr_dat$Estimate / 2))  # transform so that I can see all

# Summarize over versions (for simulated_humans)
nback_regr_dat = ddply(nback_regr_dat,
                       colnames(nback_regr_dat)[colnames(nback_regr_dat) != "version"],
                       summarize,
                       X = sID[1])
nback_regr_dat
# write.csv(nback_regr_dat, "nback_regr_dat.csv")
```
```{r Plot relationship between regressors and age and puberty}
# Plot
gg_nback_regr_agecont =
  ggplot(subset(nback_regr_dat, predictor != "(Intercept)" & back %in% seq(1, 12, 2)),
         aes(PreciseYrs, Estimate, color = predictor, fill = predictor, alpha = factor(12 - back))) +
  geom_smooth() +
  geom_point() +
  labs(x = "Age (years)", y = "P(right) ~ choice_reward", color = "Choice", fill = "Choice", alpha = "# Trials back: 12-...") +
  facet_grid(model ~ model_name)
gg_nback_regr_agecont_sig = gg_nback_regr_agecont + aes(y = sig_Estimate)

gg_nback_regr_agecats =
  ggplot(subset(nback_regr_dat, predictor != "(Intercept)"), aes(back, Estimate, color = age_group, group = age_group)) +
  # geom_point(position = "jitter", alpha = 0.15) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  stat_summary(fun.data = mean_se, geom = "line") +
  labs(x = "# trials back", y = "beta weight", color = "Side") +
  facet_grid(model_name ~ predictor)
gg_nback_regr_agecats_sig = gg_nback_regr_agecats + aes(y = sig_Estimate)

# Effect of reward and no reward on choice
rewnorew_dat = subset(nback_regr_dat, model == "rewardNoReward" & predictor != "(Intercept)")
rewnorew_dat$age_group = factor(rewnorew_dat$age_group, levels=c('7-10', '11-14', '15-17', '25-30'))
rewnorew_dat$Columbia_cat = factor(rewnorew_dat$Columbia_cat)
rewnorew_regr =
  ggplot(rewnorew_dat, aes(back, Estimate, color = age_group)) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  stat_summary(fun.data = mean_se, geom = "line") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  # scale_color_brewer(palette='Blues') +
  scale_color_manual(values=colors_3and1) +
  coord_cartesian(xlim = c(1, 9)) +
  scale_x_continuous(breaks = seq(1, 9, 2)) +
  labs(x = "Trials back", y = "Regression weight", color = "Age") +
  facet_wrap(Gender ~ predictor, scales = "free")
rewnorew_regr_PDS = rewnorew_regr + aes(color=PDS_group) + labs(color="PDS")
rewnorew_regr_T = rewnorew_regr + aes(color=T_group) + labs(color="Testost.")
rewnorew_regr_T$data = subset(rewnorew_regr$data, !is.na(T_group))

rewnorew_regr_f = rewnorew_regr +
  facet_wrap( ~ predictor, scales = "free")
rewnorew_regr_f$data = subset(rewnorew_regr$data, Gender=="Female")
rewnorew_regr_m = rewnorew_regr_f
rewnorew_regr_m$data = subset(rewnorew_regr$data, Gender=="Male")

# t.test(Estimate ~ age_group, subset(rewnorew_dat, predictor=='reward' & age_group%in%c('7-12', '13-17') & back==5))
# t.test(Estimate ~ age_group, subset(rewnorew_dat, predictor=='reward' & age_group%in%c('7-12', '25-30') & back==1))
# 
# t.test(Estimate ~ age_group, subset(rewnorew_dat, predictor=='noReward' & age_group%in%c('7-12', '13-17') & back==1))
# t.test(Estimate ~ age_group, subset(rewnorew_dat, predictor=='noReward' & age_group%in%c('7-12', '25-30') & back==1))
# t.test(subset(rewnorew_dat, predictor=='noReward' & age_group==c('13-17') & back==1)$Estimate)

# Save plots
ggsave(file.path(plot_dir, "gg_nback_regr_agecats.png"), gg_nback_regr_agecats, width=8, height=1 + 2 * length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "gg_nback_regr_agecats_sig.png"), gg_nback_regr_agecats_sig, width=8, height=1 + 2 * length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "gg_nback_regr_agecont.png"), gg_nback_regr_agecont, width=7, height=12)
ggsave(file.path(plot_dir, "gg_nback_regr_agecont_sig.png"), gg_nback_regr_agecont_sig, width=7, height=12)
ggsave(file.path(plot_dir, "rewnorew_regr.png"), rewnorew_regr, width=5, height=3 + length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "rewnorew_regr_f.png"), rewnorew_regr_f, width=5, height=1 + length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "rewnorew_regr_m.png"), rewnorew_regr_m, width=5, height=1 + length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "rewnorew_regr_PDS.png"), rewnorew_regr_PDS, width=5, height=3 + length(unique(gg_ACC_blocks$data$model_name)))
ggsave(file.path(plot_dir, "rewnorew_regr_T.png"), rewnorew_regr_T, width=5, height=3 + length(unique(gg_ACC_blocks$data$model_name)))
```
```{r Fit exponential model to regression weights}
# Visualize one example
dat = subset(nback_regr_dat, sID == unique(nback_regr_dat$sID)[1] & predictor == "reward")
# exp_mod = nls(Estimate ~ k * exp(-lambda * back), data = dat, start = list(k = .1, lambda = .1))
exp_mod = nls(Estimate ~ k * exp(-back), data = dat, start = list(k = .1))
plot(dat$back, dat$Estimate)
lines(dat$back, predict(exp_mod, list(x = dat$back)))

# Run on all participants
exp_coefs = data.frame()
for (subj in unique(nback_regr_dat$sID)) {
  for (pred in unique(nback_regr_dat$predictor[nback_regr_dat$predictor != "(Intercept)"])) {
    subj_dat = subset(nback_regr_dat, sID == subj & predictor == pred)
    exp_mod =
      try(nls(Estimate ~ k * exp(-back), data = subj_dat, start = list(k = .1)), silent = T)
    if (class(exp_mod) != "try-error") {
      subj_coefs = summary(exp_mod)$coef
      # subj_coefs = cbind(sID = subj, regr_predictor = pred, exp_predictor = rownames(subj_coefs), as.data.frame(subj_coefs, row.names = F))
      subj_coefs = cbind(sID = subj, regr_predictor = pred, exp_predictor = rownames(subj_coefs), as.data.frame(subj_coefs, row.names = '1'))
      exp_coefs = rbind(exp_coefs, subj_coefs)
    }
  }
}
exp_coefs = merge(exp_coefs, ages, all.x = T)
exp_coefs$sig_Estimate = NA
exp_coefs$sig_Estimate[exp_coefs$exp_predictor == "k"] = 1 / (1 + exp(-exp_coefs$Estimate[exp_coefs$exp_predictor == "k"] / 5))
exp_coefs$sig_Estimate[exp_coefs$exp_predictor == "lambda"] = 1 / (1 + exp(-exp_coefs$Estimate[exp_coefs$exp_predictor == "lambda"] / .5))
```
```{r Plot parameters of the exponential model}
gg_exp_coefs_age = ggplot(exp_coefs, aes(PreciseYrs, Estimate, color = regr_predictor)) +
  geom_point() +
  geom_smooth() +
  labs(y = "Regr beta ~ k * exp(-lambda * back)") +
  facet_wrap(~ exp_predictor, scale = "free")
gg_exp_coefs_age_sig = gg_exp_coefs_age + aes(y = sig_Estimate)

gg_exp_coefs_agecat =
  ggplot(subset(exp_coefs), aes(age_group, Estimate, color = regr_predictor, group = regr_predictor)) +
  geom_point(position = "jitter", alpha = 0.2) +
  stat_summary(fun.data = mean_se) +
  labs(y = "Regr beta ~ k * exp(-lambda * back)") +
  stat_summary(fun.data = mean_se, geom = "line") +
  facet_wrap(~ exp_predictor, scale = "free")
gg_exp_coefs_agecat_sig = gg_exp_coefs_agecat + aes(y = sig_Estimate)

ggsave(file.path(plot_dir, "gg_exp_coefs_age_sig.png"), gg_exp_coefs_age_sig)
ggsave(file.path(plot_dir, "gg_exp_coefs_agecat_sig.png"), gg_exp_coefs_agecat_sig)
ggsave(file.path(plot_dir, "gg_exp_coefs_age.png"), gg_exp_coefs_age)
ggsave(file.path(plot_dir, "gg_exp_coefs_agecat.png"), gg_exp_coefs_agecat)
```
```{r Relationship with age and puberty: Other measures}
# Overall ACC
sum_dat_pre = ddply(all_files, .(sID, block, version, PreciseYrs, Gender, Category, PDS), summarize,
                ACC = mean(ACC, na.rm = T),
                RT = median(RT, na.rm = T),
                stay = mean(stay, na.rm = T))
sum_dat = ddply(sum_dat_pre, .(sID, PreciseYrs, Gender, Category, PDS), summarize,
                mean_ACC = mean(ACC, na.rm = T),
                median_RT = median(RT, na.rm = T),
                n_blocks = max(block, na.rm = T),
                stay = mean(stay, na.rm = T))

gg_age_ACC =
  ggplot(sum_dat, aes(PreciseYrs, mean_ACC)) +
  geom_point() +
  geom_smooth()
gg_age_RT = gg_age_ACC + aes(y = median_RT)
gg_PDS_ACC = gg_age_ACC + aes(x = PDS)
gg_PDS_RT = gg_PDS_ACC + aes(y = median_RT)
gg_age_n_blocks = gg_age_ACC + aes(y = n_blocks)
gg_PDS_n_blocks = gg_age_n_blocks + aes(x = PDS)
gg_age_overall_stay = gg_age_ACC + aes(y = stay)
gg_PDS_overall_stay = gg_age_overall_stay + aes(x = PDS)

# Trials to reach criterion
all_files$roll_ACC = rollmean(all_files$ACC, 3, fill = NA, align = "right")
all_files$roll_ACC[all_files$trialsinceswitch >= 0 & all_files$trialsinceswitch < 2] = NA
all_files$criterion_2of3 = all_files$roll_ACC >= 0.6
criterion_dat = ddply(subset(all_files, criterion_2of3 == T & trialsinceswitch > 0), .(sID, PreciseYrs, Gender, Category, PDS, block), summarize,
      trials_to_criterion = min(trialsinceswitch))

gg_age_criterion = ggplot(criterion_dat, aes(PreciseYrs, trials_to_criterion)) +
  geom_point() +
  geom_smooth()
gg_PDS_criterion = gg_age_criterion + aes(x = PDS)

# Prominence of WSLS
wsls_wide = reshape(subset(wsls, select = -age_group), direction = "wide", timevar = "reward", idvar = "sID")
wsls_wide$wsls = with(wsls_wide, stay.1 + (1 - stay.0))
wsls_wide = merge(wsls_wide, ages, all.x = T)
wsls = merge(wsls, ages, all.x = T)

gg_age_wsls = ggplot(wsls, aes(PreciseYrs, stay, color = reward)) +
  geom_point() +
  geom_smooth()
gg_PDS_wsls = gg_age_wsls + aes(x = PDS)
```
```{r}
# Effect of reward history
rewhist_dat_pre = ddply(all_files, .(sID, version, outcome_21_back), summarize,
                    stay = mean(same_choice_01_back, na.rm = T))
rewhist_dat = ddply(rewhist_dat_pre, .(sID, outcome_21_back), summarize,
                    stay = mean(stay))
rewhist_dat = merge(rewhist_dat, ages, all.x = T)
gg_age_rewhist =
  ggplot(subset(rewhist_dat, !is.na(outcome_21_back)), aes(PreciseYrs, stay, color = outcome_21_back)) +
  geom_point() +
    geom_smooth()
gg_PDS_rewhist = gg_age_rewhist + aes(x = PDS)

# RT variability || age
RT_sd_dat = ddply(all_files, .(sID, PreciseYrs, PDS), summarize,
      RT_sd = sd(RT, na.rm = T))
gg_age_RT_sd = ggplot(RT_sd_dat, aes(PreciseYrs, RT_sd)) +
  geom_point() +
  geom_smooth()
gg_PDS_RT_sd = gg_age_RT_sd + aes(x = PDS)

# Save plots
if (gg_save) {
  ggsave(file.path(plot_dir, "gg_age_criterion.png"), gg_age_criterion)
  ggsave(file.path(plot_dir, "gg_PDS_criterion.png"), gg_PDS_criterion)
  ggsave(file.path(plot_dir, "gg_PDS_ACC.png"), gg_PDS_ACC)
  ggsave(file.path(plot_dir, "gg_age_ACC.png"), gg_age_ACC)
  ggsave(file.path(plot_dir, "gg_age_wsls.png"), gg_age_wsls)
  ggsave(file.path(plot_dir, "gg_PDS_wsls.png"), gg_PDS_wsls)
  ggsave(file.path(plot_dir, "gg_age_rewhist.png"), gg_age_rewhist)
  ggsave(file.path(plot_dir, "gg_PDS_rewhist.png"), gg_PDS_rewhist)
  ggsave(file.path(plot_dir, "gg_age_n_blocks.png"), gg_age_n_blocks)
  ggsave(file.path(plot_dir, "gg_PDS_n_blocks.png"), gg_PDS_n_blocks)
  ggsave(file.path(plot_dir, "gg_age_overall_stay.png"), gg_age_overall_stay)
  ggsave(file.path(plot_dir, "gg_PDS_overall_stay.png"), gg_PDS_overall_stay)
}

if (data != "simulated_human") {
  # RT ~ trialID || age
  RT_slope_dat = data.frame()
  for (subj in unique(all_files$sID)) {
    subj_dat = subset(all_files, sID == subj)
    RT_mod = lm(RT ~ TrialID, data = subj_dat)
    coefs = as.data.frame(summary(RT_mod)$coefficients)
    coefss = cbind(sID = subj, predictor = rownames(coefs), data.frame(coefs, row.names = NULL))
    RT_slope_dat = rbind(RT_slope_dat, rbind(coefss))
  }
  RT_slope_dat = merge(RT_slope_dat, ages, all.x = T)
  
  gg_age_RT_slope = ggplot(subset(RT_slope_dat, predictor == "TrialID"), aes(PreciseYrs, Estimate)) +# & `Pr...t..` < 0.05
    geom_point() +
    geom_smooth()
  gg_PDS_RT_slope = gg_age_RT_slope + aes(x = PDS)

  # Save plots
  if (gg_save) {
    ggsave(file.path(plot_dir, "gg_age_RT.png"), gg_age_RT)
    ggsave(file.path(plot_dir, "gg_PDS_RT.png"), gg_PDS_RT)
    ggsave(file.path(plot_dir, "gg_age_RT_sd.png"), gg_age_RT_sd)
    ggsave(file.path(plot_dir, "gg_PDS_RT_sd.png"), gg_PDS_RT_sd)
    ggsave(file.path(plot_dir, "gg_age_RT_slope.png"), gg_age_RT_slope)
  }
}
```
```{r}
mean(all_files$switch_trial)
```
```{r Start button}
```
